spring:
  application:
    name: template-application
  datasource:
    url: ${DATABASE_URL}
  r2dbc:
    url: ${R2DBC_URL}
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://test.example.com/}
          audiences: ${AUTH0_AUDIENCE:https://api.test.example.com}
